version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - aws cloudformation package --template-file resources.yaml --s3-bucket lambda-deployment-artifacts-temp --output-template-file packaged-template.yml     
artifacts:
  type: zip
  files:
    - resources.yaml
    - packaged-template.yml
    - prod-stack-configuration.json
    - test-stack-configuration.json
