AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation'
Parameters:
  S3BucketName:
    Type: String

Resources:
  OriginImageHandlerS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  
