AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation'
Parameters:
  S3BucketName:
    Type: String

Resources:
  OriginImageHandlerS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName  